// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.query.sql

package database

import (
	"context"
	"database/sql"
)

const createComment = `-- name: CreateComment :exec
INSERT INTO comments (
    id,
    post_id,
    user_id,
    parent_id,
    content
) VALUES (?, ?, ?, ?, ?)
`

type CreateCommentParams struct {
	ID       string
	PostID   string
	UserID   string
	ParentID sql.NullString
	Content  sql.NullString
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) error {
	_, err := q.db.ExecContext(ctx, createComment,
		arg.ID,
		arg.PostID,
		arg.UserID,
		arg.ParentID,
		arg.Content,
	)
	return err
}

const getPostComments = `-- name: GetPostComments :many
SELECT id, post_id, user_id, parent_id, content, created_at FROM comments
WHERE post_id = ?
ORDER BY created_at
`

func (q *Queries) GetPostComments(ctx context.Context, postID string) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, getPostComments, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.UserID,
			&i.ParentID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
