// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: follows.query.sql

package database

import (
	"context"
)

const followUser = `-- name: FollowUser :exec
INSERT INTO follows (
    follower_id, following_id
) VALUES (
    ?,?
)
`

type FollowUserParams struct {
	FollowerID  string
	FollowingID string
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) error {
	_, err := q.db.ExecContext(ctx, followUser, arg.FollowerID, arg.FollowingID)
	return err
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE FROM follows
WHERE follower_id = ?
AND following_id = ?
`

type UnfollowUserParams struct {
	FollowerID  string
	FollowingID string
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.ExecContext(ctx, unfollowUser, arg.FollowerID, arg.FollowingID)
	return err
}
