// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: follows.query.sql

package database

import (
	"context"
)

const followUser = `-- name: FollowUser :exec
INSERT INTO follows (
    follower_id, following_id
) VALUES (
    $1, $2
)
`

func (q *Queries) FollowUser(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, followUser)
	return err
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE FROM follows
WHERE follower_id = $1
AND following_id = $2
`

func (q *Queries) UnfollowUser(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, unfollowUser)
	return err
}
