// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_accounts.query.sql

package database

import (
	"context"
)

const createOAuthAccount = `-- name: CreateOAuthAccount :exec
INSERT INTO oauth_accounts (
    id,
    user_id,
    provider,
    provider_user_id
) VALUES (?, ?, ?, ?)
`

type CreateOAuthAccountParams struct {
	ID             string
	UserID         string
	Provider       string
	ProviderUserID string
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) error {
	_, err := q.db.ExecContext(ctx, createOAuthAccount,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
	)
	return err
}

const getOAuthAccount = `-- name: GetOAuthAccount :one
SELECT id, user_id, provider, provider_user_id, created_at FROM oauth_accounts
WHERE provider = $1
AND provider_user_id = $2
`

func (q *Queries) GetOAuthAccount(ctx context.Context) (OauthAccount, error) {
	row := q.db.QueryRowContext(ctx, getOAuthAccount)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
	)
	return i, err
}
