// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: otp_verifications.query.sql

package database

import (
	"context"
	"time"
)

const createOTP = `-- name: CreateOTP :exec
INSERT INTO otp_verifications (
    id,
    email,
    otp_hash,
    purpose,
    expires_at
) VALUES (?, ?, ?, ?, ?)
`

type CreateOTPParams struct {
	ID        string
	Email     string
	OtpHash   string
	Purpose   NullOtpVerificationsPurpose
	ExpiresAt time.Time
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) error {
	_, err := q.db.ExecContext(ctx, createOTP,
		arg.ID,
		arg.Email,
		arg.OtpHash,
		arg.Purpose,
		arg.ExpiresAt,
	)
	return err
}

const deleteOTP = `-- name: DeleteOTP :exec
DELETE FROM otp_verifications
WHERE id = ?
AND purpose = ?
`

type DeleteOTPParams struct {
	ID      string
	Purpose NullOtpVerificationsPurpose
}

func (q *Queries) DeleteOTP(ctx context.Context, arg DeleteOTPParams) error {
	_, err := q.db.ExecContext(ctx, deleteOTP, arg.ID, arg.Purpose)
	return err
}

const getOTP = `-- name: GetOTP :one
SELECT id, email, otp_hash, purpose, expires_at, created_at FROM otp_verifications
WHERE email = ?
AND purpose = ?
ORDER BY created_at DESC
LIMIT 1
`

type GetOTPParams struct {
	Email   string
	Purpose NullOtpVerificationsPurpose
}

func (q *Queries) GetOTP(ctx context.Context, arg GetOTPParams) (OtpVerification, error) {
	row := q.db.QueryRowContext(ctx, getOTP, arg.Email, arg.Purpose)
	var i OtpVerification
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.OtpHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
