// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.query.sql

package database

import (
	"context"
	"database/sql"
)

const createPost = `-- name: CreatePost :exec
INSERT INTO posts (
    id,
    user_id,
    content
) VALUES (?, ?, ?)
`

type CreatePostParams struct {
	ID      string
	UserID  string
	Content sql.NullString
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.ExecContext(ctx, createPost, arg.ID, arg.UserID, arg.Content)
	return err
}

const getPost = `-- name: GetPost :one
SELECT id, user_id, content, visibility, created_at FROM posts
WHERE id = ?
`

func (q *Queries) GetPost(ctx context.Context, id string) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.Visibility,
		&i.CreatedAt,
	)
	return i, err
}

const getUserPosts = `-- name: GetUserPosts :many
SELECT id, user_id, content, visibility, created_at FROM posts
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetUserPosts(ctx context.Context, userID string) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getUserPosts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.Visibility,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
