// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pre_go_crm_user_c.sql

package database

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO pre_go_acc_user_9999 (
    user_email, 
    user_mobile, 
    user_account, 
    created_at,
    user_state
) VALUES (?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	UserEmail   sql.NullString
	UserMobile  sql.NullString
	UserAccount string
	CreatedAt   sql.NullTime
	UserState   uint8
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.UserEmail,
		arg.UserMobile,
		arg.UserAccount,
		arg.CreatedAt,
		arg.UserState,
	)
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE pre_go_acc_user_9999 
SET user_state = -1 
WHERE user_id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, userID uint64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, userID)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_email, user_id 
FROM pre_go_acc_user_9999 
WHERE user_email = ? 
LIMIT 1
`

type GetUserByEmailRow struct {
	UserEmail sql.NullString
	UserID    uint64
}

func (q *Queries) GetUserByEmail(ctx context.Context, userEmail sql.NullString) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, userEmail)
	var i GetUserByEmailRow
	err := row.Scan(&i.UserEmail, &i.UserID)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT user_id, user_account, user_nickname, user_avatar, user_state, user_mobile, user_gender, user_birthday, user_email, user_is_authentication, created_at, updated_at 
FROM pre_go_acc_user_9999 
WHERE user_id = ?
`

func (q *Queries) GetUserById(ctx context.Context, userID uint64) (PreGoAccUser9999, error) {
	row := q.db.QueryRowContext(ctx, getUserById, userID)
	var i PreGoAccUser9999
	err := row.Scan(
		&i.UserID,
		&i.UserAccount,
		&i.UserNickname,
		&i.UserAvatar,
		&i.UserState,
		&i.UserMobile,
		&i.UserGender,
		&i.UserBirthday,
		&i.UserEmail,
		&i.UserIsAuthentication,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStatusByUserId = `-- name: UpdateUserStatusByUserId :exec
UPDATE pre_go_acc_user_9999 
SET user_state = ?
WHERE user_id = ?
`

type UpdateUserStatusByUserIdParams struct {
	UserState uint8
	UserID    uint64
}

func (q *Queries) UpdateUserStatusByUserId(ctx context.Context, arg UpdateUserStatusByUserIdParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatusByUserId, arg.UserState, arg.UserID)
	return err
}
