// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pre_go_crm_user_verify_c.sql

package database

import (
	"context"
	"database/sql"
)

const createUserVerify = `-- name: CreateUserVerify :execresult
INSERT INTO pre_go_acc_user_9999 (
    user_email, 
    user_mobile, 
    user_account, 
    created_at,
    user_state
) VALUES (?, ?, ?, ?, ?)
`

type CreateUserVerifyParams struct {
	UserEmail   sql.NullString
	UserMobile  sql.NullString
	UserAccount string
	CreatedAt   sql.NullTime
	UserState   uint8
}

func (q *Queries) CreateUserVerify(ctx context.Context, arg CreateUserVerifyParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUserVerify,
		arg.UserEmail,
		arg.UserMobile,
		arg.UserAccount,
		arg.CreatedAt,
		arg.UserState,
	)
}

const deleteUserVerify = `-- name: DeleteUserVerify :exec
UPDATE pre_go_acc_user_9999 
SET user_state = -1 
WHERE user_id = ?
`

func (q *Queries) DeleteUserVerify(ctx context.Context, userID uint64) error {
	_, err := q.db.ExecContext(ctx, deleteUserVerify, userID)
	return err
}

const getUserVerifyByEmail = `-- name: GetUserVerifyByEmail :one
SELECT user_email, user_id 
FROM pre_go_acc_user_9999 
WHERE user_email = ? 
LIMIT 1
`

type GetUserVerifyByEmailRow struct {
	UserEmail sql.NullString
	UserID    uint64
}

func (q *Queries) GetUserVerifyByEmail(ctx context.Context, userEmail sql.NullString) (GetUserVerifyByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserVerifyByEmail, userEmail)
	var i GetUserVerifyByEmailRow
	err := row.Scan(&i.UserEmail, &i.UserID)
	return i, err
}

const getUserVerifyById = `-- name: GetUserVerifyById :one
SELECT user_id, user_account, user_nickname, user_avatar, user_state, user_mobile, user_gender, user_birthday, user_email, user_is_authentication, created_at, updated_at 
FROM pre_go_acc_user_9999 
WHERE user_id = ?
`

func (q *Queries) GetUserVerifyById(ctx context.Context, userID uint64) (PreGoAccUser9999, error) {
	row := q.db.QueryRowContext(ctx, getUserVerifyById, userID)
	var i PreGoAccUser9999
	err := row.Scan(
		&i.UserID,
		&i.UserAccount,
		&i.UserNickname,
		&i.UserAvatar,
		&i.UserState,
		&i.UserMobile,
		&i.UserGender,
		&i.UserBirthday,
		&i.UserEmail,
		&i.UserIsAuthentication,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStatusByUserVerifyId = `-- name: UpdateUserStatusByUserVerifyId :exec
UPDATE pre_go_acc_user_9999 
SET user_state = ?
WHERE user_id = ?
`

type UpdateUserStatusByUserVerifyIdParams struct {
	UserState uint8
	UserID    uint64
}

func (q *Queries) UpdateUserStatusByUserVerifyId(ctx context.Context, arg UpdateUserStatusByUserVerifyIdParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatusByUserVerifyId, arg.UserState, arg.UserID)
	return err
}
