// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reactions.query.sql

package database

import (
	"context"
	"database/sql"
)

const createReaction = `-- name: CreateReaction :exec
INSERT INTO reactions (
    id,
    user_id,
    post_id,
    reaction_type
) VALUES (?, ?, ?, ?)
`

type CreateReactionParams struct {
	ID           string
	UserID       sql.NullString
	PostID       sql.NullString
	ReactionType sql.NullString
}

func (q *Queries) CreateReaction(ctx context.Context, arg CreateReactionParams) error {
	_, err := q.db.ExecContext(ctx, createReaction,
		arg.ID,
		arg.UserID,
		arg.PostID,
		arg.ReactionType,
	)
	return err
}

const deleteReaction = `-- name: DeleteReaction :exec
DELETE FROM reactions
WHERE user_id = $1
AND post_id = $2
`

func (q *Queries) DeleteReaction(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteReaction)
	return err
}
