// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_sessions.query.sql

package database

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO user_sessions (
    id,
    user_id,
    device_id,
    refresh_token_hash,
    expires_at
) VALUES (?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID               string
	UserID           string
	DeviceID         string
	RefreshTokenHash string
	ExpiresAt        time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.DeviceID,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
	)
	return err
}

const deleteAllSessions = `-- name: DeleteAllSessions :exec
DELETE FROM user_sessions
WHERE user_id = ?
`

func (q *Queries) DeleteAllSessions(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteAllSessions, userID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM user_sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, user_id, device_id, refresh_token_hash, expires_at, created_at FROM user_sessions
WHERE refresh_token_hash = ?
AND expires_at > NOW()
`

func (q *Queries) GetSessionByToken(ctx context.Context, refreshTokenHash string) (UserSession, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, refreshTokenHash)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
