// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_devices.query.sql

package database

import (
	"context"
	"database/sql"
)

const createDevice = `-- name: CreateDevice :exec
INSERT INTO user_devices (
    id,
    user_id,
    device_name,
    device_type,
    user_agent,
    ip_address
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateDeviceParams struct {
	ID         string
	UserID     string
	DeviceName sql.NullString
	DeviceType sql.NullString
	UserAgent  sql.NullString
	IpAddress  sql.NullString
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) error {
	_, err := q.db.ExecContext(ctx, createDevice,
		arg.ID,
		arg.UserID,
		arg.DeviceName,
		arg.DeviceType,
		arg.UserAgent,
		arg.IpAddress,
	)
	return err
}

const deleteAllDevicesByUserID = `-- name: DeleteAllDevicesByUserID :exec
DELETE FROM user_devices 
WHERE user_id = ?
`

func (q *Queries) DeleteAllDevicesByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteAllDevicesByUserID, userID)
	return err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, user_id, device_name, device_type, user_agent, ip_address, last_active, created_at
FROM user_devices
WHERE id = ?
`

func (q *Queries) GetDeviceByID(ctx context.Context, id string) (UserDevice, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByID, id)
	var i UserDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceName,
		&i.DeviceType,
		&i.UserAgent,
		&i.IpAddress,
		&i.LastActive,
		&i.CreatedAt,
	)
	return i, err
}

const listUserDevices = `-- name: ListUserDevices :many
SELECT d.id, d.user_id, d.device_name, d.device_type, d.user_agent, d.ip_address, d.last_active, d.created_at
FROM user_devices d
JOIN user_sessions s
ON s.device_id = d.id
WHERE s.user_id = ?
`

func (q *Queries) ListUserDevices(ctx context.Context, userID string) ([]UserDevice, error) {
	rows, err := q.db.QueryContext(ctx, listUserDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserDevice
	for rows.Next() {
		var i UserDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceName,
			&i.DeviceType,
			&i.UserAgent,
			&i.IpAddress,
			&i.LastActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeviceByIDAndUserID = `-- name: UpdateDeviceByIDAndUserID :exec
UPDATE user_devices
SET
    device_name = ?,
    device_type = ?,
    user_agent = ?,
    ip_address = ?,
    last_active = ?
WHERE id = ? AND user_id = ?
`

type UpdateDeviceByIDAndUserIDParams struct {
	DeviceName sql.NullString
	DeviceType sql.NullString
	UserAgent  sql.NullString
	IpAddress  sql.NullString
	LastActive sql.NullTime
	ID         string
	UserID     string
}

func (q *Queries) UpdateDeviceByIDAndUserID(ctx context.Context, arg UpdateDeviceByIDAndUserIDParams) error {
	_, err := q.db.ExecContext(ctx, updateDeviceByIDAndUserID,
		arg.DeviceName,
		arg.DeviceType,
		arg.UserAgent,
		arg.IpAddress,
		arg.LastActive,
		arg.ID,
		arg.UserID,
	)
	return err
}
