// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.query.sql

package database

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    id,
    email,
    password_hash,
    username,
    full_name
) VALUES (?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID           string
	Email        sql.NullString
	PasswordHash sql.NullString
	Username     sql.NullString
	FullName     sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Username,
		arg.FullName,
	)
	return err
}

const getEmailVerifiedStatus = `-- name: GetEmailVerifiedStatus :one
SELECT is_email_verified
FROM users
WHERE email = ?
`

func (q *Queries) GetEmailVerifiedStatus(ctx context.Context, email sql.NullString) (sql.NullBool, error) {
	row := q.db.QueryRowContext(ctx, getEmailVerifiedStatus, email)
	var is_email_verified sql.NullBool
	err := row.Scan(&is_email_verified)
	return is_email_verified, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, username, full_name, avatar_url, bio, is_email_verified, created_at FROM users
WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Bio,
		&i.IsEmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, username, full_name, avatar_url, bio, is_email_verified, created_at FROM users
WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Bio,
		&i.IsEmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, password_hash, username, full_name, avatar_url, bio, is_email_verified, created_at From users
WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Bio,
		&i.IsEmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users
SET is_email_verified = TRUE
WHERE email = ?
`

func (q *Queries) MarkEmailVerified(ctx context.Context, email sql.NullString) error {
	_, err := q.db.ExecContext(ctx, markEmailVerified, email)
	return err
}
