// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.query.sql

package database

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    id,
    email,
    password_hash,
    username,
    full_name
) VALUES (?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID           string
	Email        sql.NullString
	PasswordHash sql.NullString
	Username     sql.NullString
	FullName     sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Username,
		arg.FullName,
	)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, username, full_name, avatar_url, bio, is_email_verified, created_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Bio,
		&i.IsEmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, username, full_name, avatar_url, bio, is_email_verified, created_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Bio,
		&i.IsEmailVerified,
		&i.CreatedAt,
	)
	return i, err
}
