// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_devices.query.sql

package database

import (
	"context"
	"database/sql"
)

const createDevice = `-- name: CreateDevice :exec
INSERT INTO user_devices (
    id,
    user_id,
    device_name,
    device_type,
    user_agent,
    ip_address
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateDeviceParams struct {
	ID         string
	UserID     string
	DeviceName sql.NullString
	DeviceType sql.NullString
	UserAgent  sql.NullString
	IpAddress  sql.NullString
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) error {
	_, err := q.db.ExecContext(ctx, createDevice,
		arg.ID,
		arg.UserID,
		arg.DeviceName,
		arg.DeviceType,
		arg.UserAgent,
		arg.IpAddress,
	)
	return err
}

const listUserDevices = `-- name: ListUserDevices :many
SELECT d.id, d.user_id, d.device_name, d.device_type, d.user_agent, d.ip_address, d.last_active, d.created_at
FROM user_devices d
JOIN user_sessions s
ON s.device_id = d.id
WHERE s.user_id = $1
`

func (q *Queries) ListUserDevices(ctx context.Context) ([]UserDevice, error) {
	rows, err := q.db.QueryContext(ctx, listUserDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserDevice
	for rows.Next() {
		var i UserDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceName,
			&i.DeviceType,
			&i.UserAgent,
			&i.IpAddress,
			&i.LastActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
