// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/kien14502/ecommerce-be/internal/controllers"
	"github.com/kien14502/ecommerce-be/internal/repo"
	"github.com/kien14502/ecommerce-be/internal/services"
)

// Injectors from post.wire.go:

func InitPostRouterHandler() (*controllers.PostController, error) {
	iPostRepository := repo.NewPostRepository()
	iPostsService := services.NewPostsService(iPostRepository)
	postController := controllers.NewPostController(iPostsService)
	return postController, nil
}

// Injectors from user.wire.go:

func InitUserRouterHandler() (*controllers.UserController, error) {
	iUserRepository := repo.NewUserRepository()
	iRedisService := services.NewRedisService()
	iUserVerifyRepository := repo.NewUserVerifyRepository()
	iJwtService := services.NewJwtService()
	iUserDevicesRepository := repo.NewUserDeviceRepository()
	iUserSessionRepository := repo.NewUserSessionRepository()
	iUserService := services.NewUserService(iUserRepository, iRedisService, iUserVerifyRepository, iJwtService, iUserDevicesRepository, iUserSessionRepository)
	userController := controllers.NewUserController(iUserService)
	return userController, nil
}
