// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/kien14502/ecommerce-be/global"
	"github.com/kien14502/ecommerce-be/internal/controllers"
	"github.com/kien14502/ecommerce-be/internal/repo"
	"github.com/kien14502/ecommerce-be/internal/services"
	"github.com/kien14502/ecommerce-be/internal/sse"
)

// Injectors from sse.wire.go:

func InitSseRouterHandler() *SSEBundle {
	client := _wireClientValue
	manager := sse.NewManager(client)
	sseController := controllers.NewSSEController(manager)
	notificationService := services.NewNotificationService(manager)
	sseBundle := &SSEBundle{
		SSEController:       sseController,
		NotificationService: notificationService,
	}
	return sseBundle
}

var (
	_wireClientValue = global.Rdb
)

// Injectors from user.wire.go:

func InitUserRouterHandler() (*controllers.UserController, error) {
	iUserRepository := repo.NewUserRepository()
	iUserAuthRepository := repo.NewUserAuthRepository()
	iUserService := services.NewUserService(iUserRepository, iUserAuthRepository)
	userController := controllers.NewUserController(iUserService)
	return userController, nil
}

// sse.wire.go:

type SSEBundle struct {
	SSEController       *controllers.SSEController
	NotificationService *services.NotificationService
}
