// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Joker",
            "url": "http://www.swagger.io/support",
            "email": "stylishjoker.epu@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/sse/stream": {
            "get": {
                "description": "Establishes an SSE connection to receive real-time events for a specific user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "SSE"
                ],
                "summary": "Stream Server-Sent Events",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (defaults to 'anonymous' if not provided)",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE connection established. Events will be streamed in the format: id, event, data",
                        "schema": {
                            "type": "object"
                        },
                        "headers": {
                            "Cache-Control": {
                                "type": "string",
                                "description": "no-cache"
                            },
                            "Connection": {
                                "type": "string",
                                "description": "keep-alive"
                            },
                            "Content-Type": {
                                "type": "string",
                                "description": "text/event-stream"
                            },
                            "Transfer-Encoding": {
                                "type": "string",
                                "description": "chunked"
                            },
                            "X-Accel-Buffering": {
                                "type": "string",
                                "description": "no"
                            }
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Ecommerce API",
	Description:      "This is a sample server celler server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
